version: '1'
services: 
  node: 
    image: node:8.9.1-alpine
    depends_on: 
      - mysql
  mysql: 
    image: mysql:5.6.27
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbDocker